ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME
# Set non-interactive mode during the build
ARG DEBIAN_FRONTEND=noninteractive

######### Customize Container Here ###########

COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

COPY ./src/ubuntu/install/burp $INST_SCRIPTS/burp/
RUN bash $INST_SCRIPTS/burp/install_burp.sh && rm -rf $INST_SCRIPTS/burp/



# Set the working directory
WORKDIR /burpsuite

# Download Burp Suite JAR 


RUN wget --progress=dot:giga "https://portswigger-cdn.net/burp/releases/download?product=pro&version=2023.11.1.5&type=Jar" -O burpsuite_pro.jar


# Copy the Burp Suite Professional JAR, loader JAR files, and script to the container
COPY apps/burploader.jar apps/run_burp.sh apps/BurpBountyPro_v2.7.0.zip /burpsuite/

COPY ./src/ubuntu/install/burp/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh


# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel


######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
